version: '3'
services:
    app:
        build:
            context: node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
        tty: true
        depends_on: 
            - db
        networks:
            - fullcylcle

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/script:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_DATABASE=fullcycle
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - fullcylcle

    nginx:
        build:
            context: nginx
        container_name: nginx
        entrypoint: dockerize -wait tcp://app:3000 -timeout 20s /docker-entrypoint.sh nginx -g 'daemon off;'
        restart: always
        tty: true
        depends_on:
            - app
        ports:
            - "8080:80"
        networks:
            - fullcylcle
    
networks:
    fullcylcle:
        driver: bridge